--liquibase formatted sql

-- changeset rom:1
CREATE TABLE users
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(255) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name  VARCHAR(255) NOT NULL,
    phone      VARCHAR(255) NOT NULL,
    role       VARCHAR(255) NOT NULL DEFAULT 'USER',
    image      VARCHAR(255)
);

CREATE INDEX idx_users_email ON users (email);

COMMENT ON TABLE users IS 'Таблица с данными пользователей';
COMMENT ON COLUMN users.email IS 'Email пользователя';
COMMENT ON COLUMN users.password IS 'Пароль';
COMMENT ON COLUMN users.first_name IS 'Имя';
COMMENT ON COLUMN users.last_name IS 'Фамилия';
COMMENT ON COLUMN users.phone IS 'Телефон';
COMMENT ON COLUMN users.role IS 'Роль пользователя (USER, ADMIN)';
COMMENT ON COLUMN users.image IS 'Ссылка на аватар пользователя';

-- changeset rom:2
CREATE TABLE ad
(
    pk          INTEGER NOT NULL PRIMARY KEY,
    author      INTEGER NOT NULL,
    image       VARCHAR(255),
    price       INTEGER NOT NULL,
    title       VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL
);

CREATE INDEX idx_ad_author ON ad (author);

COMMENT ON TABLE ad IS 'Объявления пользователей';
COMMENT ON COLUMN ad.author IS 'ID автора объявления (связь с users.id)';
COMMENT ON COLUMN ad.image IS 'Ссылка на изображение объявления';
COMMENT ON COLUMN ad.price IS 'Цена объявления';
COMMENT ON COLUMN ad.title IS 'Заголовок объявления';
COMMENT ON COLUMN ad.description IS 'Описание объявления';

-- changeset rom:3
CREATE TABLE comment
(
    pk                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author            INTEGER NOT NULL,
    author_image      VARCHAR(255),
    author_first_name VARCHAR(255) NOT NULL,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    text              VARCHAR(1000) NOT NULL,
    ad_id             INTEGER
);

CREATE INDEX idx_comment_ad_id ON comment (ad_id);
CREATE INDEX idx_comment_author ON comment (author);

COMMENT ON TABLE comment IS 'Комментарии к объявлениям';
COMMENT ON COLUMN comment.author IS 'ID автора комментария';
COMMENT ON COLUMN comment.author_image IS 'Ссылка на аватар автора';
COMMENT ON COLUMN comment.author_first_name IS 'Имя автора комментария';
COMMENT ON COLUMN comment.created_at IS 'Дата и время создания комментария';
COMMENT ON COLUMN comment.text IS 'Текст комментария';
COMMENT ON COLUMN comment.ad_id IS 'ID объявления (связь с ad.pk)';

-- changeset rom:4
ALTER TABLE ad ADD CONSTRAINT fk_ad_author
    FOREIGN KEY (author) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE comment ADD CONSTRAINT fk_comment_author
    FOREIGN KEY (author) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE comment ADD CONSTRAINT fk_comment_ad
    FOREIGN KEY (ad_id) REFERENCES ad (pk) ON DELETE CASCADE;

-- changeset rom:5
ALTER TABLE users ADD CONSTRAINT chk_users_role
    CHECK (role IN ('USER', 'ADMIN'));

ALTER TABLE ad ADD CONSTRAINT chk_ad_price CHECK (price >= 0);